export type RiskLevel = "low" | "medium" | "high";
export type ContentType = "practical_reference" | "background_reference" | "medical_reference" | "mixed";
export type PreferredUse = "action_card_source" | "reference_only" | "conservative_medical_reference";

export interface KnowledgeTopic {
  id: string;
  title: string;
  summary: string;
  category: string;
  wikiUrl: string;
  iconName: string;
  riskLevel: RiskLevel;
  contentType: ContentType;
  preferredUse: PreferredUse;
}

export const KNOWLEDGE_TOPICS: KnowledgeTopic[] = [
  {
    id: "fire-making",
    title: "Fire Making",
    summary: "Techniques for starting fire in wilderness conditions",
    category: "Core Skills",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Fire_making",
    iconName: "flame-outline",
    riskLevel: "medium",
    contentType: "mixed",
    preferredUse: "action_card_source",
  },
  {
    id: "water-purification",
    title: "Water Purification",
    summary: "Methods to make water safe for drinking",
    category: "Core Skills",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Water_purification",
    iconName: "water-outline",
    riskLevel: "medium",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "first-aid",
    title: "First Aid",
    summary: "Emergency medical treatment before professional help",
    category: "Medical",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/First_aid",
    iconName: "medkit-outline",
    riskLevel: "high",
    contentType: "medical_reference",
    preferredUse: "conservative_medical_reference",
  },
  {
    id: "shelter-building",
    title: "Shelter Building",
    summary: "Constructing emergency shelters from natural materials",
    category: "Core Skills",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Survival_skills",
    iconName: "home-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "navigation",
    title: "Land Navigation",
    summary: "Finding your way without GPS or modern technology",
    category: "Navigation",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Navigation",
    iconName: "compass-outline",
    riskLevel: "low",
    contentType: "mixed",
    preferredUse: "action_card_source",
  },
  {
    id: "knot-tying",
    title: "Knot Tying",
    summary: "Essential knots for survival situations",
    category: "Core Skills",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Knot",
    iconName: "link-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "foraging",
    title: "Foraging",
    summary: "Identifying edible plants and wild food sources",
    category: "Food",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Foraging",
    iconName: "leaf-outline",
    riskLevel: "medium",
    contentType: "mixed",
    preferredUse: "action_card_source",
  },
  {
    id: "signaling",
    title: "Distress Signaling",
    summary: "Methods to signal for rescue and help",
    category: "Communication",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Distress_signal",
    iconName: "radio-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "hypothermia",
    title: "Hypothermia",
    summary: "Recognizing and treating dangerous cold exposure",
    category: "Medical",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Hypothermia",
    iconName: "snow-outline",
    riskLevel: "high",
    contentType: "medical_reference",
    preferredUse: "conservative_medical_reference",
  },
  {
    id: "dehydration",
    title: "Dehydration",
    summary: "Prevention and treatment of fluid loss",
    category: "Medical",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Dehydration",
    iconName: "water-outline",
    riskLevel: "high",
    contentType: "medical_reference",
    preferredUse: "conservative_medical_reference",
  },
  {
    id: "solar-still",
    title: "Solar Still",
    summary: "Collecting water using solar energy",
    category: "Core Skills",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Solar_still",
    iconName: "sunny-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "fishing",
    title: "Fishing Techniques",
    summary: "Catching fish for survival food",
    category: "Food",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Fishing",
    iconName: "fish-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "wound-care",
    title: "Wound Care",
    summary: "Cleaning, treating, and dressing injuries",
    category: "Medical",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Wound",
    iconName: "bandage-outline",
    riskLevel: "high",
    contentType: "medical_reference",
    preferredUse: "conservative_medical_reference",
  },
  {
    id: "cpr",
    title: "CPR",
    summary: "Cardiopulmonary resuscitation technique",
    category: "Medical",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Cardiopulmonary_resuscitation",
    iconName: "heart-outline",
    riskLevel: "high",
    contentType: "medical_reference",
    preferredUse: "conservative_medical_reference",
  },
  {
    id: "trapping",
    title: "Trapping",
    summary: "Setting traps for small game",
    category: "Food",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Trapping",
    iconName: "git-network-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "earthquake",
    title: "Earthquake Safety",
    summary: "How to survive and respond to earthquakes",
    category: "Natural Disasters",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Earthquake",
    iconName: "pulse-outline",
    riskLevel: "high",
    contentType: "mixed",
    preferredUse: "action_card_source",
  },
  {
    id: "tornado",
    title: "Tornado Safety",
    summary: "Protective actions during tornadoes",
    category: "Natural Disasters",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Tornado",
    iconName: "thunderstorm-outline",
    riskLevel: "high",
    contentType: "mixed",
    preferredUse: "action_card_source",
  },
  {
    id: "flood",
    title: "Flood Survival",
    summary: "Safety during flooding events",
    category: "Natural Disasters",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Flood",
    iconName: "rainy-outline",
    riskLevel: "high",
    contentType: "mixed",
    preferredUse: "action_card_source",
  },
  {
    id: "food-preservation",
    title: "Food Preservation",
    summary: "Methods to store food long-term",
    category: "Food",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Food_preservation",
    iconName: "nutrition-outline",
    riskLevel: "low",
    contentType: "practical_reference",
    preferredUse: "action_card_source",
  },
  {
    id: "morse-code",
    title: "Morse Code",
    summary: "Communication using dots and dashes",
    category: "Communication",
    wikiUrl: "https://en.wikipedia.org/api/rest_v1/page/summary/Morse_code",
    iconName: "chatbox-ellipses-outline",
    riskLevel: "low",
    contentType: "background_reference",
    preferredUse: "reference_only",
  },
];

export const GUIDE_MAP: Record<string, KnowledgeTopic> = Object.fromEntries(
  KNOWLEDGE_TOPICS.map((t) => [t.id, t])
);

export const CATEGORIES = [...new Set(KNOWLEDGE_TOPICS.map((t) => t.category))];
